### ISSUE TITLE
Issue while doing handshaking over BLE

### ISSUE THREAD

**Issue by Souravkumar2434** [Synss/python-mbedtls#121]
Hi, 
i am trying to establish a connection between client and server running on python-mbedtls over BLE.
I am doing certificate authentication (one-way authentication). During handshake, client is able to send CLIENT_HELLO message and server is also able to receive it and sends SERVER_HELLO. 
Since i am doing communication over BLE there is some delay in sending these messages as a result after receiving this SERVER_HELLO, client is not able to switch to CLIENT_HELLO state to send the message again to server for next steps.

If I do the communication over localhost without BLE, I am able to do handshaking and send data from Client to Server and vice-versa.

I want to do communication over BLE only which will result in some delay, what should i do to resolve it? Can you provide some insights please.

**Comment by Synss** [comment]
My guess would be you need to increase the handshake timeout. I’m not sure what BLE means either but you should know that TLS is very expensive for the processor. So if that’s related to embedded somehow, you may have a lot more bad surprises.

**Comment by Souravkumar2434** [comment]
Hi Thank you for your response for the earlier issue.
I have one more question, I want to validate the server certificates at client side, So I enabled validate_certificates as True in client side while creating DTLSConfiguration but I receive errors: mbedtls.exceptions.TLSError: TLSError([0x2700] 'X509 - Certificate verification failed, e.g. CRL, 
CA or signature check failed').

I have used the same CA certificate created by server in client.

Can you please help what I might be doing wrong in the process.
