### ISSUE TITLE
DTLS Handshake Timeout

### ISSUE THREAD

**Issue by NovaNekmit** [Synss/python-mbedtls#34]
**NOTE: Please use stackoverflow for support questions**.
This repository's issues are reserved for feature requests and bug reports.

## I am submitting a …

  - [ ] bug report
  - [x] feature request

## Description
I am trying to use DTLS for a high-latency connection (30s+), which doesn't work because the client keeps retrying the handshake with way to short delays for my application (the default is 1-60s).

### Current behavior
handshake timeout is not configurable (parameter commented out here: https://github.com/Synss/python-mbedtls/blob/master/src/mbedtls/tls.pyx#L777)

### Expected behavior

handshake timeout is configurable (somehow, preferably in DTLSConfiguration)

Binding: [mbedtls_ssl_conf_handshake_timeout](https://tls.mbed.org/api/ssl_8h.html#a6625bc4e7ffd535900ef53259cc21651)

**Comment by Synss** [comment]
Thank you for your message. That looks easy enough. I will see what I can do.

**Comment by Synss** [comment]
Should now be in master. If you want to test it, you need to install from source. I should probably keep the build artefacts but now I do not. In any case, this feature will be part of the next release. Do not hesitate to comment here if it works for you.

**Comment by NovaNekmit** [comment]
Thanks for the quick response, works great :+1:
