### ISSUE TITLE
AES CBC produce encrypted data with double length compared to Cryptodome and C mbedtls

### ISSUE THREAD

**Issue by AchmadFathoni** [Synss/python-mbedtls#37]
**NOTE: Please use stackoverflow for support questions**.
This repository's issues are reserved for feature requests and bug reports.

## I am submitting a …

  - [x] bug report
  - [ ] feature request

## Description
16 byte input data should produce 16 byte encrypted data. Cryptodome and mbedtls on my ESP32 micro controller are behaving like that. But python-mbedtls produces 32 byte encrypted data.

Here is the sample of my source code for ESP32
```
  mbedtls_aes_context aes;
  const unsigned char key[16] = "My 16-bytes key";
  unsigned char iv[16] = "My 16-bytes iv.";
  size_t length = 16;
  unsigned char in[length], out[length*2];
  for (size_t i = 0; i < length; i++) in[i] = 0;
  for (size_t i = 0; i < length*2; i++) out[i] = 0;
  
  mbedtls_aes_setkey_enc(&aes, key, 16*8);
  mbedtls_aes_crypt_cbc(&aes, MBEDTLS_AES_ENCRYPT, length,iv,in, out);

  delay(500);
  Serial.print("Encrypted from ESP32 : ");
  for (size_t i = 0; i < length*2; i++){
    Serial.printf("%d, ",(char)out[i]);
  }
  Serial.println();
```
That program print:
```
Encrypted from ESP32 : 98, 203, 172, 171, 204, 8, 236, 28, 167, 205, 120, 72, 12, 242, 72, 164, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
```
As you can see, there are 16 non zero data in output byte array of length 32.

### Current behavior
16 byte input data produces 32 byte encrypted data. The problem is python-mbedtls refuse to decrypt 16 byte encrypted data from Cryptodome and ESP32 mbedtls while giving this error
```
  File "desktop/simetrikRemote.py", line 12, in <module>
    print([int(x) for x in d.decrypt(dec_byte[:16])])
  File "src/mbedtls/cipher/_cipher.pyx", line 289, in mbedtls.cipher._cipher.Cipher.decrypt
  File "src/mbedtls/cipher/_cipher.pyx", line 276, in mbedtls.cipher._cipher.Cipher._crypt
  File "src/mbedtls/exceptions.pyx", line 54, in mbedtls.exceptions.check_error
  File "src/mbedtls/exceptions.pyx", line 57, in mbedtls.exceptions.check_error
mbedtls.exceptions.TLSError: TLSError([0x6200] 'CIPHER - Input data contains invalid padding and is rejected')`
```

### Expected behavior
16 byte input data produces 16 byte encrypted data and python-mbedtls can decrypt encryption from another AES implementation.

### Steps to reproduce

1. Encrypt using AES CBC

### Minimal demo of the problem

```
from Cryptodome.Cipher import AES
from mbedtls import cipher

key = b'My 16-bytes key\0'
iv = b"My 16-bytes iv.\0"
raw = bytearray(16) #list of zeros

d1 = AES.new(key, AES.MODE_CBC, iv)
enc1 = d1.encrypt(raw)
print("length of encrypted data using cryptodome: ", len(enc1))
print([int(x) for x in enc1])

d2 = cipher.AES.new(key, cipher.MODE_CBC, iv)
enc2 = d2.encrypt(raw)
print("length of encrypted data using python-mbedtls: ", len(enc2))
print([int(x) for x in enc2])

```

The program above prints:
```
length of encrypted data using cryptodome:  16
[98, 203, 172, 171, 204, 8, 236, 28, 167, 205, 120, 72, 12, 242, 72, 164]
length of encrypted data using python-mbedtls:  32
[98, 203, 172, 171, 204, 8, 236, 28, 167, 205, 120, 72, 12, 242, 72, 164, 204, 133, 178, 79, 207, 47, 52, 158, 254, 38, 43, 177, 175, 127, 252, 6]
```
From where that additional 16 byte come from?

## Other information
python-mbedtls : 1.4.0
OS                    : Arch Linux

**Comment by Synss** [comment]
Thank you for the report. I will have a look.

**Comment by Synss** [comment]
I am using `mbedtls_cipher_crypt` from the high-level API. That is at least one difference from your example in C. I have to investigate further.

**Comment by Synss** [comment]
Well, it really looks like a problem upstream. I have tried to translate your C program to the high-level API and obtain the 32 bytes cipher that you reported as well. This is with `libmbedtls` 2.16.8. Are you interested in reporting/fixing upstream? If not, I could have a look.

Below is the full program and its output:

```c
#include <stdio.h>
#include <string.h>
#include "mbedtls/cipher.h"

int main() {
  const unsigned char key[16] = "My 16-bytes key";
  const unsigned char iv[16] = "My 16-bytes iv.";
  size_t length = 16;

  unsigned char in[length];
  memset(in, 0, sizeof in);

  mbedtls_cipher_context_t ctx;
  mbedtls_cipher_init(&ctx);
  mbedtls_cipher_setup(&ctx, mbedtls_cipher_info_from_string("AES-128-CBC"));
  mbedtls_cipher_setkey(&ctx, key, 8 * sizeof key, MBEDTLS_ENCRYPT);

  puts(ctx.cipher_info->name);
  printf("IV size: %i\n", ctx.cipher_info->iv_size);
  printf("Block size: %i\n", ctx.cipher_info->block_size);

  unsigned char out[length + ctx.cipher_info->block_size];
  size_t olen;
  mbedtls_cipher_crypt(&ctx, iv, sizeof iv, in, sizeof in, out, &olen);

  printf("got: %zu bytes\n", olen);

  for (size_t i = 0; i < olen; i++) {
    printf("%d, ", (unsigned char)out[i]);
  }
  printf("\n");

  mbedtls_cipher_free(&ctx);
  return 0;
}
```

```
AES-128-CBC
IV size: 16
Block size: 16
got: 32 bytes
98, 203, 172, 171, 204, 8, 236, 28, 167, 205, 120, 72, 12, 242, 72, 164, 204, 133, 178, 79, 207, 47, 52, 158, 254, 38, 43, 177, 175, 127, 252, 6, 
```

**Comment by AchmadFathoni** [comment]
Thanks, I understand C/C++ and Python but I think I am incompetent to make or improve C/C++ based Python library.

**Comment by Synss** [comment]
Sure, no problem. I'll keep you updated.

**Comment by Synss** [comment]
After some more investigation: The high-level API adds a PKCS7 padding block for CBC in `mbedtls_cipher_finish()`. With `mbedtls_aes_context`, it looks like you have the possibility to [do it yourself](https://tls.mbed.org/kb/how-to/encrypt-with-aes-cbc).

Actually, `libmbedtls` has the option to *not* pad with `mbedtls_cipher_set_padding_mode( &ctx, MBEDTLS_PADDING_NONE )` but I have not bound this method yet so it is not directly available from Python.

I can add the option to set the padding, `libmbedtls` has PKCS7, ISO/IEC 7816-4, ANSI X.923, zero-padding, and no padding. Is this interesting to you?

Otherwise, you could as well use ECB, which is simpler and has no padding.

**Comment by Synss** [comment]
Also, it looks like the padding functions are private in `libmbedtls` (static in `library/cipher.c`) so it does not seem like I can make the padding option as nice as [pycrypto](https://pycryptodome.readthedocs.io/en/latest/src/util/util.html?highlight=pkcs7#Crypto.Util.Padding.pad). I will have to double check but I can probably only make it an option to the ciphers or to the encryption/decryption functions.

**Comment by Synss** [comment]
Sᴇᴄᴜʀɪᴛʏ ᴅɪsᴄʟᴀɪᴍᴇʀ: I do not encourage you to go ECB, it all depends on your application: CFB, or another cipher/mode might as well give _n_ bytes **out** for _n_ bytes **in** with better security 😅
