### ISSUE TITLE
Show whole source code 

### ISSUE THREAD

**Issue by martinapalmucci** [Synss/python-mbedtls#53]
## Description
While I was following the library code flow, 

I noticed that it was impossible to find definitions of some functions 

such as "mbedtls_pk_check_pair" (used in https://github.com/Synss/python-mbedtls/blob/master/src/mbedtls/pk.pyx, 
and declared in https://github.com/Synss/python-mbedtls/blob/master/src/mbedtls/pk.pxd). 

Please, would you help me to find all source code?

**Comment by Synss** [comment]
Hi Martina,

This library consists in Python bindings to `mbedTLS` from ARM (see upstream source code at https://github.com/ARMmbed/mbedtls/tree/v2.16.12, written in C). So what I do here is make the C implementation available in Python.

For example, you may notice that `mbedtls_pk_check_pair` is declared in a [`cdef extern from "mbedtls/pk.h" nogil:` block](https://github.com/Synss/python-mbedtls/blob/master/src/mbedtls/pk.pxd#L312) and you will find `mbedtls/pk.h` [upstream](https://github.com/ARMmbed/mbedtls/blob/v2.16.12/include/mbedtls/pk.h).

For example with `mbedtls_pk_check_pair`:
* C header upstream: [pk.h::mbedtls_pk_check_pair](https://github.com/ARMmbed/mbedtls/blob/v2.16.12/include/mbedtls/pk.h#L546-L554)
* C implementation upstream: [pk.c::mbedtls_pk_check_pair](https://github.com/ARMmbed/mbedtls/blob/v2.16.12/library/pk.c#L494-L521)

I hope that answers your question.

**Comment by martinapalmucci** [comment]
Yes, it answers my question. I appreciate your help and thank you so much for your work as well!
