### ISSUE TITLE
error control nb args

### ISSUE THREAD

**Issue by nicho2** [Synss/python-mbedtls#62]
**NOTE: Please use stackoverflow for support questions**.
This repository's issues are reserved for feature requests and bug reports.

## I am submitting a …

  - [X] bug report
  - [ ] feature request

## Description

in the file tls.py, there is an error about the length of args in function sendto (line 302)

### Current behavior

 def sendto(self, message, *args):
        if not 2 <= len(args) <= 3:
            raise TypeError(
                "sendto() takes 2 or 3 arguments (%i given)" % (1 + len(args))
            )

args can have one or two  'arg'  : flag and address also the control must be:

if not **1** <= len(args) <= **2**:

**Comment by Synss** [comment]
Indeed, you are correct. 😊
